version: '3'
services:
  remix:
    image: node:18.14.1
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
      - 5555:5555
      - 8002:8002
      - 9323:9323 # playwright reporter
    volumes:
      - .:/8bit-stack
    working_dir: /8bit-stack
    command: bash
  validate:
    image: mcr.microsoft.com/playwright:v1.35.0-jammy
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/8bit-stack
    ports:
      - 3000:3000
      - 5555:5555
      - 8002:8002
      - 9323:9323 # playwright reporter
    working_dir: /8bit-stack
    command: npm run validate
